# Generated by Django 3.2 on 2021-07-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_auto_20210714_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='archetypes',
            new_name='archetype',
        ),
    ]
